<?php

namespace Waffler\Laravel\Tests\Unit\Commands;

use Waffler\Laravel\Tests\TestCase;

/**
 * Class GenerateCodeTest.
 *
 * @author ErickJMenezes <erickmenezes.dev@gmail.com>
 * @coversNothing
 */
class GenerateCodeTest extends TestCase
{
    protected function getPackageProviders($app): array
    {
        config([
            'waffler.code_generation.openapi_files' => [
                __DIR__.'/../../../vendor/waffler/opengen/tests/Fixtures/swagger-jsonplaceholder.json' => 'JsonPlaceholder'
            ]
        ]);

        config()->set('waffler.code_generation.namespace', 'App\\Http\\Clients');

        config(['waffler.clients' => [
            'App\\Http\\Clients\\JsonPlaceholder\\UserClientInterface' => [
                'base_uri' => 'https://jsonplaceholder.typicode.com/'
            ]
        ]]);
        return parent::getPackageProviders($app); // TODO: Change the autogenerated stub
    }

    public function testItMustGenerateClasses(): void
    {
        $this->artisan('waffler:generate-code');

        $id = 'App\\Http\\Clients\\JsonPlaceholder\\UserClientInterface';
        self::assertTrue($this->app->has($id));
    }
}